package fr.bellier.testApplet;

import fr.bellier.testApplet.entities.Box;
import java.util.List;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author bruno
 */
public class Application_1 extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Application
     */
    public Application_1(int maxRow, int maxCol, TableGame game) {
        initComponents();
        initSpecific(maxRow, maxCol, game);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton14 = new javax.swing.JButton();
        contrllerJPanel = new javax.swing.JPanel();
        restartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nextStepBtn = new javax.swing.JButton();
        completeDisplayPanel = new javax.swing.JPanel();

        jButton14.setText("jButton14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        restartBtn.setText("Restart");
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });
        contrllerJPanel.add(restartBtn);

        jLabel1.setText("                                                            ");
        contrllerJPanel.add(jLabel1);

        nextStepBtn.setText("NextStep");
        nextStepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStepBtnActionPerformed(evt);
            }
        });
        contrllerJPanel.add(nextStepBtn);

        getContentPane().add(contrllerJPanel, java.awt.BorderLayout.PAGE_START);

        completeDisplayPanel.setMinimumSize(new java.awt.Dimension(202, 200));
        completeDisplayPanel.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(completeDisplayPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
        ((RandomGame) myGame).restart();
    }//GEN-LAST:event_restartBtnActionPerformed

    private void nextStepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStepBtnActionPerformed
        ((RandomGame) myGame).nextStep();
    }//GEN-LAST:event_nextStepBtnActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Application_1().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel completeDisplayPanel;
    private javax.swing.JPanel contrllerJPanel;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextStepBtn;
    private javax.swing.JButton restartBtn;
    // End of variables declaration//GEN-END:variables

    private MatrixPanel matrixPanel;
    private TableGame myGame;

    public void initSpecific(int maxRow, int maxCol, TableGame game) {
        myGame = game;
        matrixPanel = new MatrixPanel(maxRow, maxCol);
        completeDisplayPanel.add(matrixPanel);

        pack();
    }

    private void restartGame() {
        myGame = new RandomGame();
    }

    @Override
    public void update(Observable o, Object o1) {
        List<Box> boxes = (List<Box>) o1;

        for (Box box : boxes) {
            matrixPanel.setColor(box.getIndex(), box.getColor());
        }
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                repaint();
//            }
//        });
    }
}
